import React, {useEffect, useState, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowDownToLine, ArrowUpRight, BarChart3, Check, ChevronRight, CircleHelp, Database, FileText, FlaskConical, Layers3, LoaderCircle, Play, Plus, Upload, X} from 'lucide-react';
import './style.css';

const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');
let executionKey='';
const canConnect=import.meta.env.DEV||Boolean(API);
const labels={Logistica:'Regresión logística', Base_mayoritaria:'Referencia mayoritaria', PyTorch_MLP:'Red neuronal · PyTorch', Keras_LSTM:'LSTM · Keras'};
const pct=(n)=>n==null?'—':`${(n*100).toFixed(2).replace('.',',')} %`;
const num=(n)=>Number(n).toLocaleString('es-PE');
const date=(s)=>new Date(s.slice(0,10)+'T12:00:00').toLocaleDateString('es-PE',{day:'2-digit',month:'short',year:'numeric'});
async function request(path,options={}) {
  const headers=new Headers(options.headers||{});
  if(options.method==='POST'&&executionKey)headers.set('Authorization','Bearer '+executionKey);
  const res=await fetch(API+'/api'+path,{...options,headers,signal:AbortSignal.timeout(path==='/health'?90000:30000)});
  if(!res.ok){let msg=`Error ${res.status}`;try{const body=await res.json();msg=typeof body.detail==='string'?body.detail:JSON.stringify(body.detail);}catch{}throw new Error(msg);}
  return res.json();
}

function PriceChart({series,range}) {
  const [hover,setHover]=useState(null);
  let points=series;
  if(range!=='Todo'){const last=new Date(series.at(-1).date);last.setFullYear(last.getFullYear()-(range==='5 años'?5:1));points=series.filter(p=>new Date(p.date)>=last);}
  const w=880,h=270,pad=35,max=Math.max(...points.map(p=>Math.max(p.close,p.ma30)))*1.08,min=0;
  const x=i=>pad+i*(w-pad*2)/Math.max(1,points.length-1),y=v=>h-pad-(v-min)/(max-min)*(h-pad*2);
  const path=key=>points.map((p,i)=>`${x(i)},${y(p[key])}`).join(' ');
  const current=hover!=null?points[Math.min(hover,points.length-1)]:null;
  return <div className="plot"><div className="plot-reading">{current?`${date(current.date)} · Cierre ${current.close.toFixed(2)}`:'Recorre el gráfico para consultar el cierre'}</div><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Serie histórica de cierre y media móvil de 30 sesiones" onPointerLeave={()=>setHover(null)} onPointerMove={e=>{const box=e.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(points.length-1,Math.round(((e.clientX-box.left)/box.width*w-pad)/(w-2*pad)*(points.length-1)))));}}>
    <title>Cierre y media móvil de 30 sesiones</title><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#31765d" stopOpacity=".16"/><stop offset="100%" stopColor="#31765d" stopOpacity="0"/></linearGradient></defs>
    {[0,1,2,3,4].map(i=><g key={i}><line x1={pad} x2={w-pad} y1={y(max*i/4)} y2={y(max*i/4)} stroke="#e7e9e4" strokeDasharray="3 5"/><text x={pad-9} y={y(max*i/4)+4} textAnchor="end">{(max*i/4).toFixed(0)}</text></g>)}
    <polygon points={`${pad},${h-pad} ${path('close')} ${w-pad},${h-pad}`} fill="url(#fill)"/>
    <polyline points={path('close')} fill="none" stroke="#23664f" strokeWidth="2.4" strokeLinejoin="round"/>
    <polyline points={path('ma30')} fill="none" stroke="#be9b5b" strokeWidth="1.5" opacity=".8"/>
    {[0,.25,.5,.75,1].map((v,i)=>{const idx=Math.round((points.length-1)*v);return <text key={i} x={x(idx)} y={h-7} textAnchor="middle">{points[idx].date.slice(0,7)}</text>;})}
    {current&&<g><line x1={x(hover)} x2={x(hover)} y1={pad} y2={h-pad} stroke="#88978c" strokeDasharray="4"/><circle cx={x(hover)} cy={y(current.close)} r="4" fill="#23664f" stroke="white" strokeWidth="2"/></g>}
  </svg><div className="legend"><span><i/>Cierre</span><span><i className="gold"/>Media de 30 sesiones</span><small>Vista resumida · valores del CSV</small></div></div>;
}

function App(){
  const [data,setData]=useState(null),[live,setLive]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [view,setView]=useState('resumen'),[range,setRange]=useState('Todo'),[model,setModel]=useState('Keras_LSTM');
  const [runId,setRunId]=useState('actual'),[runs,setRuns]=useState([]),[job,setJob]=useState(null),[panel,setPanel]=useState(false);
  const [file,setFile]=useState(null),[uploading,setUploading]=useState(false),[mode,setMode]=useState('base'),[epochs,setEpochs]=useState(30),[submitting,setSubmitting]=useState(false);
  const [keyRequired,setKeyRequired]=useState(false),[defaultCsv,setDefaultCsv]=useState(true),[snapshot,setSnapshot]=useState(true);
  const [allowedModes,setAllowedModes]=useState(['base']);
  const [connectionAttempt,setConnectionAttempt]=useState(0);
  const dialog=useRef(null);
  const loadRun=async id=>{setLoading(true);setError('');try{const value=await request('/dashboard/'+id);setData(value);setSnapshot(false);setRunId(id);setModel(Object.hasOwn(value.summary.metricas_test,model)?model:Object.keys(value.summary.metricas_test)[0]);}catch(e){setError(e.message);}finally{setLoading(false);}};
  useEffect(()=>{
    let alive=true,retry;
    (async()=>{
      try {
        const cached=await fetch('/demo/dashboard.json');
        if(cached.ok&&alive&&connectionAttempt===0){setData(await cached.json());setSnapshot(true);setLoading(false);}
      } catch {}
      if(!canConnect){if(alive)setLoading(false);return;}
      try {
        const health=await request('/health');
        if(health.service!=='mercado-lab')throw new Error('La URL no corresponde al motor de Mercado Lab.');
        if(!alive)return;
        setLive(true);setError('');setKeyRequired(Boolean(health.key_required));
        setDefaultCsv(health.default_csv_available!==false);
        const modes=health.allowed_modes||['base','completo'];
        setAllowedModes(modes);setMode(current=>modes.includes(current)?current:'base');
        setRuns(await request('/runs'));
        if(health.active)setJob(await request('/runs/'+health.active));
        else setJob(null);
        try {const current=await request('/dashboard/actual');if(alive){setData(current);setSnapshot(false);}}catch{}
      } catch(e){if(alive){setLive(false);setError('El servidor no responde. Reintentaremos la conexión automáticamente; los resultados guardados siguen disponibles. '+e.message);retry=setTimeout(()=>setConnectionAttempt(n=>n+1),10000);}}
      finally{if(alive)setLoading(false);}
    })();
    return()=>{alive=false;clearTimeout(retry);};
  },[connectionAttempt]);
  useEffect(()=>{
    if(!job||job.status!=='running')return;
    let stopped=false,timer;
    const poll=async()=>{
      let delay=4000;
      try{
        const state=await request('/runs/'+job.id);
        if(stopped)return;
        setError('');setJob(state);
        if(state.status==='completed'){await loadRun(state.id);setRuns(await request('/runs'));return;}
        if(state.status==='failed'){setError(state.error);return;}
      }catch(e){if(stopped)return;delay=10000;setError('No se pudo actualizar el progreso. Reintentando; el análisis podría seguir ejecutándose. '+e.message);}
      if(!stopped)timer=setTimeout(poll,delay);
    };
    timer=setTimeout(poll,4000);
    return()=>{stopped=true;clearTimeout(timer);};
  },[job?.id,job?.status]);
  useEffect(()=>{if(panel&&!dialog.current?.open)dialog.current?.showModal();else if(!panel&&dialog.current?.open)dialog.current.close();},[panel]);
  useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'consultar_metricas_mercado',description:'Lee las métricas del análisis que aparece en el panel.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({analisis:runId,metricas:data?.summary.metricas_test||{},estado:job?.status||'idle'})},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[data,runId,job?.status]);
  async function upload(e){const f=e.target.files?.[0];if(!f)return;setUploading(true);setError('');setFile(null);try{const form=new FormData();form.append('file',f);setFile(await request('/upload',{method:'POST',body:form}));}catch(err){setError(err.message);}finally{setUploading(false);e.target.value='';}}
  async function start(e){e.preventDefault();setSubmitting(true);setError('');try{const value=await request('/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,epochs:Number(epochs),upload_id:file?.id||null})});setJob(value);setPanel(false);}catch(err){setError(err.message);}finally{setSubmitting(false);}}
  const artifact=(name)=>live&&!snapshot?`${API}/api/artifacts/${runId}/${name}`:`/demo/${name}`;
  const s=data?.summary,m=s?.metricas_test[model]||Object.values(s?.metricas_test||{})[0],activeName=s?.metricas_test[model]?model:Object.keys(s?.metricas_test||{})[0];
  const busy=job?.status==='running';
  return <div className="app-shell"><aside className="sidebar"><a href="#" className="brand" onClick={e=>{e.preventDefault();setView('resumen');}}><div className="brand-icon"><Activity size={24}/></div><span>mercado<span className="brand-light">lab</span><small>FINANCIAL INTELLIGENCE</small></span></a><div className="workspace"><span className="workspace-badge">G</span><div>Proyecto financiero<small>PIAD-425 · Machine Learning</small></div></div><div className="nav-label">ESPACIO DE ANÁLISIS</div><nav aria-label="Principal">{[['resumen',BarChart3,'Resumen'],['modelos',Layers3,'Modelos'],['texto',FileText,'Análisis de texto'],['datos',Database,'Datos']].map(([key,Icon,label])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)} aria-current={view===key?'page':undefined}><Icon size={19}/>{label}{key===view&&<ChevronRight size={15}/>}</button>)}</nav><div className="sidebar-bottom"><div className="research-note"><FlaskConical size={20}/><strong>Un espacio para experimentar.</strong><p>Compara modelos y entiende los datos detrás de cada predicción.</p></div><span className="sidebar-foot">PROYECTO ACADÉMICO <span>v1.0</span></span></div></aside>
  <main className="main"><header className="topbar"><div className="breadcrumbs">Espacio de trabajo <ChevronRight size={14}/><strong>{({resumen:'Resumen',modelos:'Modelos',texto:'Análisis de texto',datos:'Datos'})[view]}</strong></div><span className={'connection '+(live?'online':'')}><i/>{live?'Motor conectado':'Resultados guardados'}</span></header>
  <div className="content"><div className="page-heading"><div><div className="eyebrow">MERCADO LAB / {view==='texto'?'REPORTES FINANCIEROS':'EXPLORACIÓN FINANCIERA'}</div><h1>{({resumen:'Del dato a la tendencia.',modelos:'Compara. Evalúa. Comprende.',texto:'Lo que dicen los reportes.',datos:'El origen del análisis.'})[view]}</h1><p>{({resumen:'Una mirada a tus datos y al desempeño de tus modelos.',modelos:'Mismas fechas de prueba. Distintas formas de aprender.',texto:'Términos y cifras extraídos de documentación financiera.',datos:'Revisa el dataset y cómo se distribuye en el tiempo.'})[view]}</p></div><button className="primary" onClick={()=>setPanel(true)} disabled={!live||busy} title={!live?'Conecta el servidor Python para ejecutar nuevos análisis.':''}><Plus size={18}/>Nuevo análisis</button></div>
  {!live&&!loading&&<div className="notice"><CircleHelp size={18}/><span>{API?'El backend remoto no está conectado. Si está despertando, espera y vuelve a intentar.':'Consulta de resultados guardados. Configura VITE_API_URL para conectar un backend remoto o inicia el servicio local.'} <button className="text-button" onClick={()=>window.location.reload()}>Reintentar conexión</button></span></div>}
  {error&&<div className="error" role="alert"><span>{error}</span><button aria-label="Cerrar aviso" onClick={()=>setError('')}><X size={18}/></button></div>}
  {job&&<div className={'job '+job.status} role="status"><div>{busy?<LoaderCircle className="spin" size={19}/>:job.status==='completed'?<Check size={19}/>:<CircleHelp size={19}/>}<strong>{busy?'Análisis en ejecución':job.status==='completed'?'Análisis completado':'No se pudo completar el análisis'}</strong></div><p>{busy?'Puedes seguir consultando los resultados anteriores. Esta vista se actualizará al terminar.':job.status==='completed'?'Ya puedes explorar los nuevos resultados.':job.error}</p><details><summary>Registro de ejecución</summary><pre>{job.log||'Preparando datos…'}</pre></details></div>}
  {loading&&!data?<div className="empty"><LoaderCircle className="spin"/><h2>Cargando el análisis…</h2></div>:!data?<div className="empty"><Database size={40}/><h2>Aún no hay resultados</h2><p>Inicia un nuevo análisis con el dataset del proyecto.</p></div>:<>
  <div className="dataset-strip"><div className="ticker">{s.datos.ticker}</div><div><strong>{s.datos.ticker==='GGAL'?'Grupo Financiero Galicia':s.datos.ticker}</strong><small>{date(s.datos.inicio)} — {date(s.datos.fin)}</small></div><span className="dataset-divider"/><span><strong>{num(s.datos.filas_utiles)}</strong> observaciones</span><span className="pill">{s.configuracion.modo==='completo'?'Análisis completo':'Análisis base'}</span>{live&&<select aria-label="Análisis visible" value={runId} disabled={loading} onChange={e=>loadRun(e.target.value)}><option value="actual">Resultados del proyecto</option>{runs.filter(r=>r.status==='completed').map(r=><option key={r.id} value={r.id}>{r.dataset} · {new Date(r.created).toLocaleString('es-PE')}</option>)}{runId!=='actual'&&!runs.some(r=>r.id===runId)&&<option value={runId}>Análisis reciente</option>}</select>}</div>
  {view==='resumen'&&<><div className="section-line"><h2>En perspectiva</h2><label className="model-select">Modelo <select value={activeName} onChange={e=>setModel(e.target.value)}>{Object.keys(s.metricas_test).map(name=><option key={name} value={name}>{labels[name]||name}</option>)}</select></label></div><div className="stats"><div className="stat"><span>Exactitud <Activity size={17}/></span><strong>{pct(m.exactitud)}</strong><small>Aciertos sobre el conjunto de prueba</small></div><div className="stat"><span>Subidas detectadas <ArrowUpRight size={17}/></span><strong>{m.matriz_confusion[1][1]} <em>/ {num(m.matriz_confusion[1].reduce((a,b)=>a+b,0))}</em></strong><small>Recall de {pct(m.recall)}</small></div><div className="stat"><span>F1 de la clase subida <Layers3 size={17}/></span><strong>{m.f1.toFixed(3)}</strong><small>Equilibrio entre precision y recall</small></div><div className="stat accent-stat"><span>Observaciones de prueba <Database size={17}/></span><strong>{num(s.datos.particiones.test.filas)}</strong><small>Reservadas para evaluación final</small></div></div>
  <section className="card chart-card"><div className="card-head"><div><h2>Evolución del mercado</h2><p>Precio de cierre y tendencia histórica</p></div><div className="segmented" aria-label="Período del gráfico">{['1 año','5 años','Todo'].map(r=><button aria-pressed={r===range} className={r===range?'selected':''} key={r} onClick={()=>setRange(r)}>{r}</button>)}</div></div><PriceChart series={data.series} range={range}/></section>
  <div className="bottom-grid"><section className="card"><div className="card-head"><h2>Una comparación honesta</h2><button className="text-button" onClick={()=>setView('modelos')}>Ver modelos <ArrowUpRight size={16}/></button></div><div className="model-bars">{Object.entries(s.metricas_test).map(([name,v])=><div className="model-bar" key={name}><span>{labels[name]||name}</span><div><i style={{width:`${v.exactitud*100}%`}}/></div><strong>{pct(v.exactitud)}</strong></div>)}</div><p className="caption">Exactitud en prueba. Más complejidad no garantiza mejores predicciones.</p></section><section className="insight"><span className="insight-label"><CircleHelp size={17}/> LECTURA DEL RESULTADO</span><h2>La exactitud es solo una parte.</h2><p>{labels[activeName]} detectó <strong>{m.matriz_confusion[1][1]} subidas</strong> de {num(m.matriz_confusion[1].reduce((a,b)=>a+b,0))}. Revisa también recall y F1 antes de interpretar el desempeño.</p><button className="text-button" onClick={()=>setView('modelos')}>Explorar la evaluación <ArrowUpRight size={17}/></button></section></div></>}
  {view==='modelos'&&<><section className="card"><div className="card-head"><div><h2>Resultados en prueba</h2><p>Clase positiva: el cierre de la siguiente sesión sube</p></div><a className="secondary" href={artifact('metricas.csv')} download><ArrowDownToLine size={16}/>Descargar CSV</a></div><div className="table-wrap"><table><thead><tr><th>Modelo</th><th>Exactitud</th><th>Precision</th><th>Recall</th><th>F1</th><th>ROC-AUC</th></tr></thead><tbody>{Object.entries(s.metricas_test).map(([name,v])=><tr key={name}><th><span className="model-dot"/>{labels[name]||name}</th>{['exactitud','precision','recall','f1','roc_auc'].map(k=><td key={k}>{v[k]==null?'—':v[k].toFixed(4)}</td>)}</tr>)}</tbody></table></div><p className="caption">La referencia predice la clase mayoritaria de entrenamiento. El período de prueba no selecciona los parámetros.</p></section><section className="card image-card"><h2>¿Dónde se equivoca cada modelo?</h2><p>Filas: clase real. Columnas: clase predicha.</p><img src={artifact('graficos/matrices_confusion.png')} alt="Matrices de confusión de todos los modelos"/></section><div className="two-grid">{data.graphs.filter(n=>n.startsWith('aprendizaje_')).map(name=><section className="card image-card" key={name}><h2>{name.includes('Keras')?'Aprendizaje de la LSTM':'Aprendizaje de PyTorch'}</h2><img src={artifact('graficos/'+name)} alt="Pérdidas de entrenamiento y validación por época" loading="lazy"/></section>)}</div><section className="card image-card"><h2>Tendencia observada y probabilidades</h2><img src={artifact('graficos/tendencias_predichas.png')} alt="Comparación temporal de tendencias observadas y predicciones" loading="lazy"/></section></>}
  {view==='texto'&&<><div className="stats three"><div className="stat"><span>Páginas analizadas <FileText size={17}/></span><strong>{num(s.nlp.paginas_analizadas)}</strong><small>Páginas con texto suficiente</small></div><div className="stat"><span>Tokens filtrados <Layers3 size={17}/></span><strong>{num(s.nlp.tokens)}</strong><small>Palabras después de la limpieza</small></div><div className="stat accent-stat"><span>Vocabulario <BarChart3 size={17}/></span><strong>{num(s.nlp.vocabulario)}</strong><small>Términos distintos</small></div></div><div className="two-grid"><section className="card"><div className="card-head"><div><h2>Términos relevantes</h2><p>Peso TF-IDF medio por página</p></div></div><div className="term-bars">{data.terms.slice(0,10).map(t=><div key={t.termino}><span>{t.termino}</span><div><i style={{width:`${Number(t.tfidf_medio)/Number(data.terms[0].tfidf_medio)*100}%`}}/></div><small>{Number(t.tfidf_medio).toFixed(3)}</small></div>)}</div></section><section className="card"><div className="card-head"><h2>Documentos de origen</h2></div>{s.nlp.fuentes.map(source=><div className="source" key={source.archivo}><FileText size={28}/><h3>{source.titulo}</h3><p>Publicación: {date(source.fecha_publicacion)} · Inglés</p><a href={source.url} target="_blank" rel="noreferrer">Consultar reporte original <ArrowUpRight size={16}/></a></div>)}<div className="note"><strong>Análisis independiente</strong><p>Este reporte se publicó después del período del CSV. No se usa como predictor histórico. La tokenización no equivale a un análisis de sentimiento.</p></div><a className="secondary" href={artifact('nlp_paginas.csv')} download><ArrowDownToLine size={16}/>Descargar cifras por página</a></section></div></>}
  {view==='datos'&&<><section className="card"><div className="card-head"><div><h2>Preparación del dataset</h2><p>Validación, indicadores y separación cronológica</p></div><button className="secondary" disabled={!live||busy} onClick={()=>setPanel(true)}><Upload size={17}/>Cargar otro CSV</button></div><div className="data-counts"><div><strong>{num(s.datos.filas_originales)}</strong><span>Registros originales</span></div><ChevronRight/><div><strong>{num(s.datos.filas_descartadas)}</strong><span>Filas descartadas</span></div><ChevronRight/><div><strong>{num(s.datos.filas_utiles)}</strong><span>Observaciones útiles</span></div></div><div className="split-bar"><span style={{flex:6}}>Entrenamiento</span><span style={{flex:2}}>Validación</span><span style={{flex:2}}>Prueba</span></div><div className="split-labels">{Object.entries(s.datos.particiones).map(([key,v])=><div key={key}><strong>{num(v.filas)} filas</strong><small>{date(v.inicio)} — {date(v.fin)}</small></div>)}</div><p className="caption">División aproximada 60/20/20. Se purga una etiqueta en cada frontera para evitar cruces temporales.</p></section><section className="card"><div className="card-head"><h2>Vista previa de datos preparados</h2><span className="muted">Primeras 8 filas</span></div><div className="table-wrap"><table><thead><tr>{['Fecha','Cierre','Volumen','Retorno','Objetivo'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data.preview.map(row=><tr key={row.Date}><td>{row.Date.slice(0,10)}</td><td>{Number(row.close).toFixed(2)}</td><td>{num(row.volume)}</td><td>{pct(Number(row.Retorno))}</td><td><span className={'target '+(row.Objetivo==='1'?'up':'')}>{row.Objetivo==='1'?'Sube':'Baja / igual'}</span></td></tr>)}</tbody></table></div></section><div className="notice"><CircleHelp size={19}/><span>El CSV original fue recibido con el proyecto. Su proveedor y licencia no están verificados. Una carga nueva tampoco verifica automáticamente la procedencia.</span></div></>}
  <footer><span>Calculado el {date(s.fecha_utc)} · Semilla {s.configuracion.seed}</span><a href={artifact('INFORME_TECNICO.html')} target="_blank" rel="noreferrer">Abrir informe técnico <ArrowUpRight size={16}/></a></footer></>}
  </div></main>
  <dialog ref={dialog} onCancel={()=>setPanel(false)} onClick={e=>{if(e.target===dialog.current)setPanel(false);}}><form onSubmit={start}><div className="dialog-heading"><div><span className="eyebrow">EXPERIMENTO LOCAL</span><h2>Nuevo análisis</h2></div><button type="button" className="icon-button" aria-label="Cerrar" onClick={()=>setPanel(false)}><X/></button></div><p>Prepara datos, entrena modelos y genera un nuevo informe.</p>{keyRequired&&<label className="field-label">Clave de ejecución<input type="password" autoComplete="off" aria-label="Clave de ejecución" placeholder="Clave compartida por el grupo" onChange={e=>{executionKey=e.target.value;}} style={{display:'block',width:'100%',padding:12,margin:'8px 0 18px',border:'1px solid #dce4d1',borderRadius:6}}/><small>Se utiliza para cargar archivos y ejecutar modelos.</small></label>}<label className="field-label">Dataset</label><div className="upload-box"><Upload size={26}/><strong>{uploading?'Validando archivo…':file?file.name:defaultCsv?'Usar CSV original de GGAL':'Selecciona un CSV para continuar'}</strong><span>{file?`${num(file.audit.filas_utiles)} observaciones · ${file.audit.ticker}`:'O selecciona un CSV de un solo activo (máximo 10 MB).'}</span><label className="secondary upload-label">{uploading?'Validando…':'Seleccionar archivo'}<input type="file" accept=".csv" aria-label="Seleccionar archivo CSV" disabled={uploading||busy} onChange={upload}/></label>{file&&<button type="button" className="text-button" onClick={()=>setFile(null)}>Volver al CSV original</button>}</div><p className="field-help">Columnas: Date (o primera columna sin nombre), open, high, low, close, volume y ticker. Mínimo 150 filas útiles.</p><div className="form-row"><label>Modelos<select value={mode} onChange={e=>setMode(e.target.value)}><option value="completo" disabled={!allowedModes.includes('completo')}>{allowedModes.includes('completo')?'Todos · logística, PyTorch y LSTM':'Todos · no disponible en este servidor'}</option><option value="base">Base · logística y referencia</option></select></label><label>Épocas máximas<input type="number" value={epochs} min="1" max="50" required disabled={mode==='base'} onChange={e=>setEpochs(e.target.value)}/></label></div><div className="note"><strong>Los resultados anteriores se conservan.</strong><p>Cada análisis se guarda por separado. El reporte de texto seguirá siendo el documento de Galicia incluido en el proyecto.</p></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary full" type="submit" disabled={uploading||submitting||busy||!live||(!defaultCsv&&!file)}>{submitting?<LoaderCircle className="spin" size={18}/>:<Play size={17}/>}Ejecutar análisis</button></form></dialog>
  </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
